"""was added column 'role'

Revision ID: d457d855b202
Revises: 2a588f1b4613
Create Date: 2026-08-09 19:56:52.152158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd457d855b202'
down_revision: Union[str, Sequence[str], None] = '2a588f1b4613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='roles', native_enum=False), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
