"""тщту

Revision ID: e3d769ebbe18
Revises: eb4e51e0659f
Create Date: 2026-07-30 15:50:21.087447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d769ebbe18'
down_revision: Union[str, Sequence[str], None] = 'eb4e51e0659f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adderss', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('CartItems_product_id_fkey'), 'CartItems', type_='foreignkey')
    op.create_foreign_key(None, 'CartItems', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CartItems', type_='foreignkey')
    op.create_foreign_key(op.f('CartItems_product_id_fkey'), 'CartItems', 'products', ['product_id'], ['id'])
    op.drop_table('detail_order')
    op.drop_table('orders')
    # ### end Alembic commands ###
