"""hi

Revision ID: eb4e51e0659f
Revises: 47a8c6dd5d52
Create Date: 2026-07-23 22:03:15.600930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4e51e0659f'
down_revision: Union[str, Sequence[str], None] = '47a8c6dd5d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('CartItems_user_id_fkey'), 'CartItems', type_='foreignkey')
    op.create_foreign_key(None, 'CartItems', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CartItems', type_='foreignkey')
    op.create_foreign_key(op.f('CartItems_user_id_fkey'), 'CartItems', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
